name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar APK dentro do Container
        run: |
          buildozer android debug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: binance-bot-apk
          path: bin/*.apk
          
